/* `node cli.js parts` — the whole catalogue as text an agent can read in one shot. */
module.exports = function partsRef(KNEX, json) {
  var K = KNEX.KINDS, L = KNEX.LADDER, D = KNEX.DIMS;
  if (json) return JSON.stringify({ dims: D, kinds: K, ladder: L, flexi: KNEX.FLEXI }, null, 1);
  var out = [];
  out.push("K'NEX classic catalogue — units mm, lattice U = " + D.U + " (green c2c)");
  out.push("");
  out.push("RODS  colour   c2c     length  units    side-on?");
  L.forEach(function (l) { out.push("      " + l.color.padEnd(8) + String(l.c2c).padEnd(8) + String(l.len).padEnd(8) + l.units.toFixed(4).padEnd(9) + (l.ridges ? "yes, anywhere on the ribbed body" : "NO (green is smooth)")); });
  out.push("      c2c = 37.5 * sqrt(2)^(n-1); length = c2c - 20. Any distance not on this ladder cannot be built.");
  out.push("      flexi rods exist in: " + Object.keys(KNEX.FLEXI).join(", ") + " (they bow when the span is shorter than the rod)");
  out.push("");
  out.push("CONNECTORS  code  name                  sockets            notes");
  Object.keys(K).forEach(function (k) { out.push("            " + k.padEnd(6) + K[k].name.padEnd(22) + K[k].slots.join(",").padEnd(19) + (K[k].cross ? "3D: extra perpendicular slot, mates with another 3D" : "")); });
  out.push("      socket k points at 45*k degrees from slot 0, measured in the connector's plane, counter-clockwise about its normal.");
  out.push("      disc " + (2 * D.connR) + " across, " + D.connT + " thick, hub hole " + D.hubHoleD + ", socket floor " + D.d + " from the centre.");
  out.push("");
  out.push("JOINTS (inferred from geometry, never declared)");
  out.push("  end-on  rod tip in a socket .................. RIGID");
  out.push("  hub     rod through the centre hole ......... FREE AXLE: spins + slides. park with spacers " + D.spacer.blue + " / " + D.spacer.silver);
  out.push("  side-on connector clipped onto a rod ........ PIVOT WITH FRICTION about the rod; hub sits " + D.sideR + " off the rod axis");
  out.push("          the four ribs run LENGTHWISE down the rod, so a clip goes anywhere except the smooth 9 mm ends");
  out.push("  3D pair two 3D connectors, planes at 90 ..... RIGID corner in three axes");
  out.push("");
  out.push("STIFFNESS  cantilever k = 3EI/L^3, E " + D.E + " MPa (flexi " + D.Eflexi + "), I " + D.I + " mm^4 (estimate)");
  L.forEach(function (l) { out.push("      " + l.color.padEnd(8) + (3 * D.E * D.I / Math.pow(l.len, 3)).toFixed(2).padStart(7) + " N/mm" + (KNEX.FLEXI[l.color] ? "   flexi " + (3 * D.Eflexi * D.Iflexi / Math.pow(l.len, 3)).toFixed(2) + " N/mm" : "")); });
  out.push("");
  out.push("PHYSICS (node cli.js sim build.knx)");
  out.push("  Bodies come from the rigid partition: end-on joints and 3D pairs weld parts into one body.");
  out.push("  A hub joint is a real bearing between two bodies: it spins, and it slides unless a spacer, a cap or");
  out.push("  another connector sits within 12 mm of it on the same rod.");
  out.push("  Rods marked `beam` are force elements, not structure: rigid along their length, springy across it");
  out.push("  (k = 12EI/L^3 with both ends in sockets, 3EI/L^3 when the far end is a hub that can slide).");
  out.push("  Flexi rods buckle: once the span is shorter than the rod they push their ends apart with a nearly");
  out.push("  constant Pcr = pi^2 EI / L^2, and they pull hard once taut. Pcr for a flexi yellow is about 8 N,");
  out.push("  which is far more than a small model weighs, so a compressed flexi will preload joints badly.");
  out.push("  The desk is a contact plane with Coulomb friction. Props with a mass are rigid boxes that collide");
  out.push("  with the model, so a gripper only moves them once it actually touches.");
  out.push("  Surfaces (mouse feet / K'NEX feet): " + Object.keys(KNEX.SURFACES).map(function (k) { return k + " " + KNEX.SURFACES[k].mu + "/" + KNEX.SURFACES[k].muKnex; }).join("  "));
  out.push("  Estimates, not measurements: flexi modulus " + D.Eflexi + " MPa, rod I " + D.I + " mm^4, socket pull-out " + D.socketPull + " N,");
  out.push("  hub friction " + D.muHub + ". Treat force numbers as ratios and trends, not as certified values.");
  out.push("");
  out.push("BUILD RULES");
  out.push("  1. Work in lattice units. Integer coordinates give green/blue/red spans; diagonals give white/yellow/grey.");
  out.push("  2. A distance of 3 U does not exist. Split it (2+1) with a connector in between.");
  out.push("  3. A connector's plane holds rods in 8 directions only. Rods along its normal go through the hub and spin free.");
  out.push("  4. To turn a corner in all three axes you need a 3D pair (B7/P4) or a side-on clip, never a lone W8.");
  out.push("  5. Triangulate every square: the diagonal of an n x n square is the next rod up the ladder.");
  out.push("  6. Orange O2 has no side sockets: keep it out of load paths, but it is the right part where a");
  out.push("     connector's extra arms would foul something, because it only has two.");
  out.push("  7. Pick the connector by the directions you need. Every arm is 18.75 mm long and it is real: a W8");
  out.push("     whose plane is vertical reaches the desk if its centre is 18.75 mm up, and its unused arms will");
  out.push("     hit whatever is next to it. R3 covers a 90 degree corner, G4 135, Y5 180, O2 a straight line.");
  out.push("  8. A rod end with no connector stops 10 mm short of the point you declared: that point is where a");
  out.push("     connector's centre would be, not where the plastic ends.");
  return out.join("\n");
};
